name: CI Orso Backend

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: pdo, pdo_mysql

    - name: Install Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        php composer.phar install

    - name: Dump Autoload
      run: php composer.phar dump-autoload -o

    - name: Debug folder (cek penting!)
      run: ls -R

    - name: Run PHPUnit
      run: php vendor/bin/phpunit